### ISSUE TITLE
Proposal : Editable animation duration

### ISSUE THREAD

**Issue by LeadcodeDev** [nank1ro/flutter-shadcn-ui#85] opened 2024-06-30 18:01 UTC
Hello,

Thank you for your work.

I'd like to suggest an improvement to the speed of execution of animations, particularly on the `Popover` and `Select` components.

It would be interesting to allow the `transition-duration` to be modified so that we can make the UI more or less dynamic.
```dart
ShadSelect<String>(
  animationDuration: Duration(),
  decoration: const ShadDecoration(
    color: Colors.white,
  ),
  placeholder: const Text('Select a fruit'),
    options: fruits.entries
      .map((e) => ShadOption(value: e.key, child: Text(e.value)))
      .toList(),
  selectedOptionBuilder: (context, value) => Text(fruits[value]!),
),
```

Looking forward to seeing you,

**Comment by nank1ro** [comment] 2024-06-30 18:04
Duplicate of https://github.com/nank1ro/flutter-shadcn-ui/issues/73
It's already feasible, see how I commented in the other issue

**Closed** 2024-06-30 18:05 UTC
